language: go

go:
  - 1.2
  - tip

before_install:
  - sudo apt-get install graphicsmagick
  - sudo apt-get install redis-server
  - go get code.google.com/p/go.tools/cmd/cover

script:
  - go test -v -cover ./...
  - go test -v -run=Benchmark -bench=. -benchmem ./...