language: go

go:
  - 1.3.1
  - tip

services:
  - memcached
  - redis-server

before_install:
  - sudo apt-get install graphicsmagick
  - export PATH=$PATH:$GOROOT/bin:/home/travis/gopath/bin #ugly hack
  - go get -v code.google.com/p/go.tools/cmd/cover
  - go get -v code.google.com/p/go.tools/cmd/goimports
  - go get -v github.com/golang/lint/golint

script:
  - go test -v -cover ./...
  - find . -type d | grep -v ".git" | xargs -L 1 golint
  - goimports -l .
