language: go

go:
  - 1.2.1
  - tip

services:
  - memcached
  - redis-server

before_install:
  - sudo apt-get install graphicsmagick
  - go get -v code.google.com/p/go.tools/cmd/cover
  - go get -v code.google.com/p/go.tools/cmd/goimports
  - go get -v github.com/golang/lint/golint
  - export PATH=$PATH:/home/travis/gopath/bin #ugly hack

script:
  - go test -v -cover ./...
  - go test -v -run=Benchmark -bench=. -benchmem ./...
  - golint .
  - goimports -l .
